//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Resources/Scripts/Input/InputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""210000d4-837d-44ee-b41d-d96b6520af75"",
            ""actions"": [
                {
                    ""name"": ""Open Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""ebcbae47-97de-4595-878c-c5bb99b36a63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""3e775014-0083-4939-9016-7466496b97db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn Item"",
                    ""type"": ""Button"",
                    ""id"": ""e512cc7c-8256-42c8-be2e-479a8287de24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Remove Item"",
                    ""type"": ""Button"",
                    ""id"": ""0ccff91f-2be0-492b-8ddd-d6af88345feb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GetHalfStackOfItems"",
                    ""type"": ""Button"",
                    ""id"": ""03e6976c-0f33-4c7c-9384-df69b556c426"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GetItemsWithScroll"",
                    ""type"": ""Button"",
                    ""id"": ""6a1be7a3-480f-4cff-9a01-a4fff97ec6ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveForwardAndBackward"",
                    ""type"": ""Button"",
                    ""id"": ""14752315-b4ed-4bcd-bb31-db0b194feb58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRightAndLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1661d645-3cd9-43ef-8666-62fe900002c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""b8f0d307-647b-4677-8c39-a1a1b114b82e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemSpawner"",
                    ""type"": ""Button"",
                    ""id"": ""950e89b2-66c0-43be-bc31-34563d637bb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""46ea277d-4267-4d7e-9e5b-fa59a182f09c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open Context Menu"",
                    ""type"": ""Button"",
                    ""id"": ""4612244c-bb5d-4f3e-9e7a-946a5c9f5f09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""3c70648e-8a1f-432d-a070-fd2feb2c1aff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""592e24b8-3cb4-4fab-bb7b-b02c9b6ea2b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisableScrollingInView"",
                    ""type"": ""Button"",
                    ""id"": ""251e61c9-65da-4997-8da0-d732ebaa99cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7d337dd8-f13c-4fbe-b5cf-ea731305ebc0"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7af28de4-359e-415f-a425-80b1755bab34"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""289739e2-64f0-438c-bd2a-e28d40e8decc"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d16bda78-a838-442c-b31f-d67db0f2c2da"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Remove Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b37889e1-b7bd-4bec-a920-6052aa42e3e4"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetHalfStackOfItems"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2a145caa-a1a5-4a63-b077-07c0db3dd538"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetItemsWithScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""bc6846a4-c17a-4b55-b086-07f10901871b"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetItemsWithScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""65796d29-0759-4f5d-9b0b-3a011fa00067"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""GetItemsWithScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""40948ba5-ebbb-41ef-a8f1-89398cd934e1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardAndBackward"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""eda4e13c-794f-4869-80d3-b7828e130722"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardAndBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""45af557f-9888-4b42-b7b5-d46a050b1103"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardAndBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""85e644ef-0d11-45c1-a405-f850e5073f9d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRightAndLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f8965f15-f351-4908-92bd-731310f8ea57"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRightAndLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""829f913c-18b7-4328-ab0b-d66c9295f85d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRightAndLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""21c946e9-7a6e-4da9-9971-553767afeac7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c242fd2a-81ef-47b8-97d1-1d9d3e8c7495"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSpawner"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c41ac916-4200-4ca3-8831-36a2af9c732c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""299b149c-89ae-4a12-a607-9355d7a3d580"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Context Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff3b65b7-9b9c-4a4d-b1b2-eb9dae237604"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53c19661-4daa-4a52-8936-7b561237df37"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da726b4d-242e-441f-beb3-3201b2934db3"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisableScrollingInView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_OpenInventory = m_Player.FindAction("Open Inventory", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_SpawnItem = m_Player.FindAction("Spawn Item", throwIfNotFound: true);
        m_Player_RemoveItem = m_Player.FindAction("Remove Item", throwIfNotFound: true);
        m_Player_GetHalfStackOfItems = m_Player.FindAction("GetHalfStackOfItems", throwIfNotFound: true);
        m_Player_GetItemsWithScroll = m_Player.FindAction("GetItemsWithScroll", throwIfNotFound: true);
        m_Player_MoveForwardAndBackward = m_Player.FindAction("MoveForwardAndBackward", throwIfNotFound: true);
        m_Player_MoveRightAndLeft = m_Player.FindAction("MoveRightAndLeft", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_ItemSpawner = m_Player.FindAction("ItemSpawner", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_OpenContextMenu = m_Player.FindAction("Open Context Menu", throwIfNotFound: true);
        m_Player_Escape = m_Player.FindAction("Escape", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_DisableScrollingInView = m_Player.FindAction("DisableScrollingInView", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_OpenInventory;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_SpawnItem;
    private readonly InputAction m_Player_RemoveItem;
    private readonly InputAction m_Player_GetHalfStackOfItems;
    private readonly InputAction m_Player_GetItemsWithScroll;
    private readonly InputAction m_Player_MoveForwardAndBackward;
    private readonly InputAction m_Player_MoveRightAndLeft;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_ItemSpawner;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_OpenContextMenu;
    private readonly InputAction m_Player_Escape;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_DisableScrollingInView;
    public struct PlayerActions
    {
        private @InputSystem m_Wrapper;
        public PlayerActions(@InputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenInventory => m_Wrapper.m_Player_OpenInventory;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @SpawnItem => m_Wrapper.m_Player_SpawnItem;
        public InputAction @RemoveItem => m_Wrapper.m_Player_RemoveItem;
        public InputAction @GetHalfStackOfItems => m_Wrapper.m_Player_GetHalfStackOfItems;
        public InputAction @GetItemsWithScroll => m_Wrapper.m_Player_GetItemsWithScroll;
        public InputAction @MoveForwardAndBackward => m_Wrapper.m_Player_MoveForwardAndBackward;
        public InputAction @MoveRightAndLeft => m_Wrapper.m_Player_MoveRightAndLeft;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @ItemSpawner => m_Wrapper.m_Player_ItemSpawner;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @OpenContextMenu => m_Wrapper.m_Player_OpenContextMenu;
        public InputAction @Escape => m_Wrapper.m_Player_Escape;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @DisableScrollingInView => m_Wrapper.m_Player_DisableScrollingInView;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @OpenInventory.started += instance.OnOpenInventory;
            @OpenInventory.performed += instance.OnOpenInventory;
            @OpenInventory.canceled += instance.OnOpenInventory;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @SpawnItem.started += instance.OnSpawnItem;
            @SpawnItem.performed += instance.OnSpawnItem;
            @SpawnItem.canceled += instance.OnSpawnItem;
            @RemoveItem.started += instance.OnRemoveItem;
            @RemoveItem.performed += instance.OnRemoveItem;
            @RemoveItem.canceled += instance.OnRemoveItem;
            @GetHalfStackOfItems.started += instance.OnGetHalfStackOfItems;
            @GetHalfStackOfItems.performed += instance.OnGetHalfStackOfItems;
            @GetHalfStackOfItems.canceled += instance.OnGetHalfStackOfItems;
            @GetItemsWithScroll.started += instance.OnGetItemsWithScroll;
            @GetItemsWithScroll.performed += instance.OnGetItemsWithScroll;
            @GetItemsWithScroll.canceled += instance.OnGetItemsWithScroll;
            @MoveForwardAndBackward.started += instance.OnMoveForwardAndBackward;
            @MoveForwardAndBackward.performed += instance.OnMoveForwardAndBackward;
            @MoveForwardAndBackward.canceled += instance.OnMoveForwardAndBackward;
            @MoveRightAndLeft.started += instance.OnMoveRightAndLeft;
            @MoveRightAndLeft.performed += instance.OnMoveRightAndLeft;
            @MoveRightAndLeft.canceled += instance.OnMoveRightAndLeft;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @ItemSpawner.started += instance.OnItemSpawner;
            @ItemSpawner.performed += instance.OnItemSpawner;
            @ItemSpawner.canceled += instance.OnItemSpawner;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @OpenContextMenu.started += instance.OnOpenContextMenu;
            @OpenContextMenu.performed += instance.OnOpenContextMenu;
            @OpenContextMenu.canceled += instance.OnOpenContextMenu;
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @DisableScrollingInView.started += instance.OnDisableScrollingInView;
            @DisableScrollingInView.performed += instance.OnDisableScrollingInView;
            @DisableScrollingInView.canceled += instance.OnDisableScrollingInView;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @OpenInventory.started -= instance.OnOpenInventory;
            @OpenInventory.performed -= instance.OnOpenInventory;
            @OpenInventory.canceled -= instance.OnOpenInventory;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @SpawnItem.started -= instance.OnSpawnItem;
            @SpawnItem.performed -= instance.OnSpawnItem;
            @SpawnItem.canceled -= instance.OnSpawnItem;
            @RemoveItem.started -= instance.OnRemoveItem;
            @RemoveItem.performed -= instance.OnRemoveItem;
            @RemoveItem.canceled -= instance.OnRemoveItem;
            @GetHalfStackOfItems.started -= instance.OnGetHalfStackOfItems;
            @GetHalfStackOfItems.performed -= instance.OnGetHalfStackOfItems;
            @GetHalfStackOfItems.canceled -= instance.OnGetHalfStackOfItems;
            @GetItemsWithScroll.started -= instance.OnGetItemsWithScroll;
            @GetItemsWithScroll.performed -= instance.OnGetItemsWithScroll;
            @GetItemsWithScroll.canceled -= instance.OnGetItemsWithScroll;
            @MoveForwardAndBackward.started -= instance.OnMoveForwardAndBackward;
            @MoveForwardAndBackward.performed -= instance.OnMoveForwardAndBackward;
            @MoveForwardAndBackward.canceled -= instance.OnMoveForwardAndBackward;
            @MoveRightAndLeft.started -= instance.OnMoveRightAndLeft;
            @MoveRightAndLeft.performed -= instance.OnMoveRightAndLeft;
            @MoveRightAndLeft.canceled -= instance.OnMoveRightAndLeft;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @ItemSpawner.started -= instance.OnItemSpawner;
            @ItemSpawner.performed -= instance.OnItemSpawner;
            @ItemSpawner.canceled -= instance.OnItemSpawner;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @OpenContextMenu.started -= instance.OnOpenContextMenu;
            @OpenContextMenu.performed -= instance.OnOpenContextMenu;
            @OpenContextMenu.canceled -= instance.OnOpenContextMenu;
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @DisableScrollingInView.started -= instance.OnDisableScrollingInView;
            @DisableScrollingInView.performed -= instance.OnDisableScrollingInView;
            @DisableScrollingInView.canceled -= instance.OnDisableScrollingInView;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnSpawnItem(InputAction.CallbackContext context);
        void OnRemoveItem(InputAction.CallbackContext context);
        void OnGetHalfStackOfItems(InputAction.CallbackContext context);
        void OnGetItemsWithScroll(InputAction.CallbackContext context);
        void OnMoveForwardAndBackward(InputAction.CallbackContext context);
        void OnMoveRightAndLeft(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnItemSpawner(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnOpenContextMenu(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDisableScrollingInView(InputAction.CallbackContext context);
    }
}
